build: 
	g++ -I/usr/local/include/opencv4 -L/usr/local/lib/ -lopencv_core -lopencv_imgproc -lopencv_imgcodecs -lopencv_objdetect -lopencv_features2d -lopencv_xfeatures2d -lopencv_calib3d deskew_with_reference.cpp
	g++ -I/usr/local/include/opencv4 -L/usr/local/lib/ -lopencv_core -lopencv_imgproc -lopencv_imgcodecs -lopencv_objdetect -lopencv_features2d -lopencv_xfeatures2d -lopencv_highgui deskew_auto.cpp


